### ISSUE TITLE
checkbag plugin fix

### ISSUE THREAD

**Issue by pacenadhif778** [1242509682/GodCheck#2]
please fix the detection on the plugin because the server that has posted golem, the item from brain of cthulhu/eater of worlds (evil boss) is detected as an illegal item, use the bestiary to be more accurate and also create a configuration for exception items (whitelist items)

**Comment by 1242509682** [comment]
Did you suggest the wrong place? That plugin has a configuration file that can modify the item ID for each stage

**Comment by pacenadhif777** [comment]
> Did you suggest the wrong place? That plugin has a configuration file that can modify the item ID for each stage

okay but can you fix the problem of item detection due to progress world that is already hardmode and has entered post golem, items from pre hardmode are detected illegally by the plugin in the configuration is just a list of items not whitelist items.

**Comment by pacenadhif778** [comment]
I am using the latest version and it is still the same
![Screenshot_20241209-185518](https://github.com/user-attachments/assets/31f80a15-fe43-4bbf-84da-7725b623925d)
![Screenshot_20241209-185529](https://github.com/user-attachments/assets/750c720f-326f-42b3-bf14-76498f47d894)
![Screenshot_20241209-185534](https://github.com/user-attachments/assets/b38d4a51-6b4f-47b0-94c4-196a798b3be5)

**Comment by 1242509682** [comment]
> I am using the latest version and it is still the same ![Screenshot_20241209-185518](https://private-user-images.githubusercontent.com/189197860/393788660-31f80a15-fe43-4bbf-84da-7725b623925d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDk2MzksIm5iZiI6MTczMzkwOTMzOSwicGF0aCI6Ii8xODkxOTc4NjAvMzkzNzg4NjYwLTMxZjgwYTE1LWZlNDMtNGJiZi04NGRhLTc3MjViNjIzOTI1ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwOTI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTRjYzQ2M2I2MmQ5OTE3OWIzMWIxOWQ1NjAyMTU5YWVlNjIyYzczY2M2ZTNlODljOTI5MDY1NTIyYjJjY2NlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jkj67sE3Gi-RjzgtgrxXyhWYdcwsY5fJnuXC_YQBK4Q) ![Screenshot_20241209-185529](https://private-user-images.githubusercontent.com/189197860/393788716-750c720f-326f-42b3-bf14-76498f47d894.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDk2MzksIm5iZiI6MTczMzkwOTMzOSwicGF0aCI6Ii8xODkxOTc4NjAvMzkzNzg4NzE2LTc1MGM3MjBmLTMyNmYtNDJiMy1iZjE0LTc2NDk4ZjQ3ZDg5NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwOTI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjhiMjNhZDExMDQ1Mzg3OWU2ZDZiYTlhMzFiOGQ1OTEzYzE1MTBhMDE4MWVkMGI5N2ZhODdjZDhmY2MzZDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3sf8CWoi9kCSQDTf-zv_7ACUfIeNPM9zu31nzYCx2bk) ![Screenshot_20241209-185534](https://private-user-images.githubusercontent.com/189197860/393788811-b38d4a51-6b4f-47b0-94c4-196a798b3be5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDk2MzksIm5iZiI6MTczMzkwOTMzOSwicGF0aCI6Ii8xODkxOTc4NjAvMzkzNzg4ODExLWIzOGQ0YTUxLTZiNGYtNDdiMC05NGM0LTE5NmE3OThiM2JlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwOTI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGU0NjRkYzVkYjAwMjc5ZTkwN2NhODMxYTlmNDk3NjVjZTNhYjBkMDE3N2FmNTk0MjRhYTRkM2QxYTg3M2QxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pUu0g0FNlcMJzLycCbB5pnCvZP4SSn_AKS7AV6pdV3I)

我已经对Checkbag重构，请删除现有的配置文件后，使用最新版：[检查背包](https://github.com/1242509682/TShockCheckBag/releases/tag/2.7.0)
